# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mr7zvdABrj7T_ybe6LJHFi1pZdm3BNHG
"""

a = int(input("Masukkan angka: "))
while a >= 0:
    print(a, end=' ')
    a = a-1

def hitung_mundur(angka):
    for i in range(angka, -1, -1):
        print(i, end=' ')

input_angka = input("Masukkan angka: ")
if input_angka.isdigit():
    angka = int(input_angka)
    hitung_mundur(angka)
else:
    print("Input harus berupa angka.")

suhu = float(input("Masukkan suhu dalam derajat Celcius: "))

if suhu < 0:
    print("Membeku")
elif suhu < 10:
    print("Sangat Dingin")
elif suhu < 20:
    print("Sejuk")
elif suhu < 30:
    print("Hangat")
elif suhu < 40:
    print("Panas")
else:
    print("Sangat Panas")

def adalah_prima(angka):
    if angka <= 1:
        return False
    for i in range(2, int(angka**0.5) + 1):
        if angka % i == 0:
            return False
    return True

input_angka = input("Masukkan angka: ")
if input_angka.isdigit():
    angka = int(input_angka)
    if adalah_prima(angka):
        print(f"{angka} adalah angka prima.")
    else:
        print(f"{angka} bukan angka prima.")
else:
    print("Input harus berupa angka.")

def lingkaran():
    print("Menghitung Luas Lingkaran")
    r = float(input("Masukan jari jari: "))

    Luas = (3.14 * r * r)
    Keliling = (2 * 3.14 * r)

    print("Luas lingkaran =", Luas)
    print("Keliling lingkaran =", Keliling)

lingkaran()

def niu():
  niu = int(input("Masukkan NIU: "))
  while len(str(niu)) != 6:
    print("NIU harus berisi 6 angka!!!")
    niu = int(input("Masukkan NIU: "))
  return (niu)

def nilai():
  nilai_tugas = int(input("Masukkan Nilai Ujian: "))
  nilai_laporan = int(input("Masukkan Nilai Laporan: "))
  rata_rata_nilai = (nilai_tugas + nilai_laporan) / 2
  if rata_rata_nilai < 40:
    print("Nilai siswa K")
  else:
    nilai_ujian = int(input("Masukkan Nilai Ujian: "))
    nilai_akhir = (nilai_tugas * 0.25) + (nilai_laporan * 0.25) + (nilai_ujian * 0.5)
    if nilai_akhir >= 80:
        print("Nilai siswa: A")
    elif nilai_akhir >= 70:
        print("Nilai siswa: B")
    elif nilai_akhir >= 60:
        print("Nilai siswa: C")
    elif nilai_akhir >= 50:
        print("Nilai siswa: D")
    else:
        print("Nilai siswa: E")

def main():
  niu()
  nilai()

if __name__=="__main__":
  main()